---
title: "On-Demand"
author: "Mingze Li 300137754"
date: "2025-02-04"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mvtnorm)
library(traveltimeCLT)
library(data.table)
library(dplyr)
library(ggplot2)
library(traveltimeHMM)
library(lubridate)
library(patchwork)
```

```{r}
log_no_0 <- function(x) {
  l <- length(x)
  result <- c()
  for (i in 1:l) {
    if (x[i] == 0) {
      result <- c(result, 0)
    } else {
      result <- c(result, log(x[i]))
    }
  }
  result
}
sd_na_is_0 <- function(x) {
  if (length(x) >= 2) {
    return(sd(x, na.rm = T))
  } else {
    return(0)
  }
}
```

## Sample data

```{r}
trips <- fread("data/trips.csv")
trips$time <- as.POSIXct(trips$time, format = "%Y-%m-%dT%H:%M:%OSZ")
trips$timeBin <- time_bins_readable(trips$time)
trips[, duration_secs := as.numeric(difftime(shift(time, type = "lead"), time, units = "secs")), by = trip]
trips[, log_duration := log(duration_secs)]
trips <- na.omit(trips)
timeBin_x_edges <- trips[,
  .(
    mean = mean(log_duration, na.rm = TRUE),
    sd = sd_na_is_0(log_duration),
    frequency = .N
  ),
  by = .(linkId, timeBin)
]
timeBin_x_edges[, edge := 1:.N]
# sample 1000 trips
set.seed(1234)
id <- sample(unique(trips$trip), 1000)
sampled_trips <- trips[trip %in% id, .(trip, linkId, timeBin, duration_secs, logspeed, length, time)]
sampled_trips <- merge(sampled_trips, timeBin_x_edges, by = c("linkId", "timeBin"), all.x = TRUE)
sampled_time <- sampled_trips[, .(sum(duration_secs, rm.na = T)), by = "trip"]
names(sampled_time)[2] <- "sampled_time"
sampled_trips <- data.frame(sampled_trips)
```

## Non-dependence model
```{r}
non_dependent_simulator <- function(edges, rho = 0.31) {
  l <- length(edges)
  U <- runif(l)
  mu <- (sampled_trips[match(edges, sampled_trips$edge), 8])
  sigma <- (sampled_trips[match(edges, sampled_trips$edge), 9])
  sum(exp(mu + sigma * qnorm(U)))
}
non_dependent_time <- sampled_trips %>%
  group_by(trip) %>%
  summarise(simulated_time = non_dependent_simulator(edge))
travel_time <- data.frame(sampled_time)
travel_time$non_dependent_time <- non_dependent_time$simulated_time
```

```{r}
plot1 <- ggplot(travel_time) +
  stat_ecdf(aes(x = sampled_time, color = "sampled data")) +
  stat_ecdf(aes(x = non_dependent_time, color = "non dependent data")) +
  labs(title = "CDF of Travel Time", x = "Total Travel Time (seconds)", y = "Cumulative Probability") +
  coord_cartesian(xlim = c(0, 4000), ylim = c(0, 1)) +
  scale_color_manual(
    name = "Legend",
    values = c(
      "sampled data" = "red",
      "dependent data" = "black",
      "non dependent data" = "black",
      "first order data" = "black",
      "second order data" = "black",
      "population data" = "black",
      "HMM model simulation" = "black"
    )
  ) +
  theme(
    legend.position = c(0.95, 0.5),
    legend.justification = c(1, 1),
    legend.text.align = 0,
    legend.background = element_rect(color = "black", fill = "white")
  )
plot1
```




## Population model

```{r}
population_simulator <- function(duration_secs) {
  l <- length(duration_secs) + 1
  Z <- rnorm(l, 0, sqrt(1))
  mu <- mean(duration_secs)
  sigma <- sd_na_is_0(duration_secs)
  t <- numeric(l)
  for (i in 2:l) {
    t[i] <- t[i - 1] + mu + sigma * Z[i]
  }
  t[l]
}
population_time <- sampled_trips %>%
  group_by(trip) %>%
  summarise(simulated_time = population_simulator(duration_secs))
travel_time$population_time <- population_time$simulated_time
```

```{r}
plot3 <- ggplot(travel_time) +
  stat_ecdf(aes(x = sampled_time, color = "sampled data")) +
  stat_ecdf(aes(x = population_time, color = "population data")) +
  labs(title = "CDF of Travel Time", x = "Total Travel Time (seconds)", y = "Cumulative Probability") +
  coord_cartesian(xlim = c(0, 4000), ylim = c(0, 1)) +
  scale_color_manual(
    name = "Legend",
    values = c(
      "sampled data" = "red",
      "dependent data" = "black",
      "non dependent data" = "black",
      "first order data" = "black",
      "second order data" = "black",
      "population data" = "black",
      "HMM model simulation" = "black"
    )
  ) +
  theme(
    legend.position = c(0.95, 0.5),
    legend.justification = c(1, 1),
    legend.text.align = 0,
    legend.background = element_rect(color = "black", fill = "white")
  )
plot3
```
## First Order Model

```{r}
first_order <- function(n, rho = 0.31) {
  S <- diag(n)
  if (n > 1) {
    for (i in 1:n) {
      if (i - 1 > 0) S[i, (i - 1)] <- rho
      if (i + 1 <= n) S[i, (i + 1)] <- rho
    }
    diag(S) <- 1
    eigen_values <- eigen(S, symmetric = TRUE)$values
    if (!all(eigen_values >= 0)) {
      S <- as.matrix(Matrix::nearPD(S, cor = TRUE)$mat)
    }
    U <- c(pnorm(rmvnorm(1, sigma = S)))
  } else {
    U <- runif(1)
  }
  U
}
first_order_simulator <- function(edges, rho = 0.31) {
  l <- length(edges)
  U <- first_order(l)
  mu <- (sampled_trips[match(edges, sampled_trips$edge), 8])
  sigma <- (sampled_trips[match(edges, sampled_trips$edge), 9])
  sum(exp(mu + sigma * qnorm(U)))
}
first_order_time <- sampled_trips %>%
  group_by(trip) %>%
  summarise(simulated_time = first_order_simulator(edge))
travel_time$first_order_time <- first_order_time$simulated_time
```

```{r}
plot4 <- ggplot(travel_time) +
  stat_ecdf(aes(x = sampled_time, color = "sampled data")) +
  stat_ecdf(aes(x = first_order_time, color = "first order data")) +
  labs(title = "CDF of Travel Time", x = "Total Travel Time (seconds)", y = "Cumulative Probability") +
  coord_cartesian(xlim = c(0, 4000), ylim = c(0, 1)) +
  scale_color_manual(
    name = "Legend",
    values = c(
      "sampled data" = "red",
      "dependent data" = "black",
      "non dependent data" = "black",
      "first order data" = "black",
      "second order data" = "black",
      "population data" = "black",
      "HMM model simulation" = "black"
    )
  ) +
  theme(
    legend.position = c(0.95, 0.5),
    legend.justification = c(1, 1),
    legend.text.align = 0,
    legend.background = element_rect(color = "black", fill = "white")
  )
plot4
```
## Second Order Model

```{r}
second_order <- function(n, rho = 0.31) {
  S <- diag(n)
  if (n > 2) {
    for (i in 1:n) {
      if (i - 2 > 0) S[i, (i - 2)] <- rho^2
      if (i + 2 <= n) S[i, (i + 2)] <- rho^2
      if (i - 1 > 0) S[i, (i - 1)] <- rho
      if (i + 1 <= n) S[i, (i + 1)] <- rho
    }
    S[1, 3] <- rho
    S[3, 1] <- rho
    diag(S) <- 1
    eigen_values <- eigen(S, symmetric = TRUE)$values
    if (!all(eigen_values >= 0)) {
      S <- as.matrix(Matrix::nearPD(S, cor = TRUE)$mat)
    }
    U <- c(pnorm(rmvnorm(1, sigma = S)))
  } else {
    U <- runif(n)
  }
  U
}
second_order_simulator <- function(edges, rho = 0.31) {
  l <- length(edges)
  U <- second_order(l)
  mu <- (sampled_trips[match(edges, sampled_trips$edge), 8])
  sigma <- (sampled_trips[match(edges, sampled_trips$edge), 9])
  sum(exp(mu + sigma * qnorm(U)))
}
second_order_time <- sampled_trips %>%
  group_by(trip) %>%
  summarise(simulated_time = second_order_simulator(edge))
travel_time$second_order_time <- first_order_time$simulated_time
```

```{r}
plot5 <- ggplot(travel_time) +
  stat_ecdf(aes(x = sampled_time, color = "sampled data")) +
  stat_ecdf(aes(x = second_order_time, color = "second order data")) +
  labs(title = "CDF of Travel Time", x = "Total Travel Time (seconds)", y = "Cumulative Probability") +
  coord_cartesian(xlim = c(0, 4000), ylim = c(0, 1)) +
  scale_color_manual(
    name = "Legend",
    values = c(
      "sampled data" = "red",
      "dependent data" = "black",
      "non dependent data" = "black",
      "first order data" = "black",
      "second order data" = "black",
      "population data" = "black",
      "HMM model simulation" = "black"
    )
  ) +
  theme(
    legend.position = c(0.95, 0.5),
    legend.justification = c(1, 1),
    legend.text.align = 0,
    legend.background = element_rect(color = "black", fill = "white")
  )
plot5
```

```{r}
tripdata <- data.frame(
  logspeed = sampled_trips$logspeed,
  tripID = sampled_trips$trip,
  timeBin = sampled_trips$timeBin,
  linkID = sampled_trips$linkId,
  length = sampled_trips$length,
  time = (sampled_trips$time),
  traveltime = sampled_trips$duration_secs
)
tripdata <- tripdata %>%
  group_by(tripID) %>%
  arrange(time, .by_group = TRUE)
unique(tripdata$timeBin)

tripdata$time <- as.POSIXct(tripdata$time, format = "%Y-%m-%dT%H:%M:%OSZ")
tripdata$timeBin <- time_bins_readable(tripdata$time)
unique(tripdata$timeBin)
```


```{r}
fit <- traveltimeHMM(
  data = tripdata,
  nQ = 2, max.it = 20, model = "HMM"
)
single_trip <- subset(tripdata, tripID == unique(tripdata$tripID)[1])
```


```{r}
pred <- predict(
  object = fit,
  tripdata = single_trip,
  starttime = single_trip$time[1],
  n = 1000
)
hist(pred, freq = FALSE)
travel_time$HMM <- pred
```

```{r}
ggplot(travel_time) +
  stat_ecdf(aes(x = sampled_time, color = "sampled data")) +
  stat_ecdf(aes(x = pred, color = "HMM model simulation")) +
  labs(title = "CDF of Travel Time", x = "Total Travel Time (seconds)", y = "Cumulative Probability") +
  coord_cartesian(xlim = c(0, 4000), ylim = c(0, 1)) +
  scale_color_manual(name = "Legend", values = c("black", "red"))
```

```{r}
starttime <- tripdata %>%
  group_by(tripID) %>%
  summarise(first(time))
pred <- c()
for (i in 1:1000) {
  single_trip <- subset(tripdata, tripID == unique(tripdata$tripID)[i])
  newpred <- predict(
    object = fit,
    tripdata = single_trip,
    starttime = starttime$`first(time)`[i],
    n = 1
  )
  pred <- c(pred, newpred)
}
travel_time$HMM <- pred
```

```{r}
plot6 <- ggplot(travel_time) +
  stat_ecdf(aes(x = sampled_time, color = "sampled data")) +
  stat_ecdf(aes(x = pred, color = "HMM model simulation")) +
  labs(title = "CDF of Travel Time", x = "Total Travel Time (seconds)", y = "Cumulative Probability") +
  coord_cartesian(xlim = c(0, 4000), ylim = c(0, 1)) +
  scale_color_manual(
    name = "Legend",
    values = c(
      "sampled data" = "red",
      "dependent data" = "black",
      "non dependent data" = "black",
      "first order data" = "black",
      "second order data" = "black",
      "population data" = "black",
      "HMM model simulation" = "black"
    )
  ) +
  theme(
    legend.position = c(0.95, 0.5),
    legend.justification = c(1, 1),
    legend.text.align = 0,
    legend.background = element_rect(color = "black", fill = "white")
  )
plot6
```

```{r}
plot_list <- list(plot1, plot2, plot4, plot5, plot3, plot6)
combined_plot <- wrap_plots(plot_list, nrow = 3)


ggsave("plot/R_combined_simulation_plots3.jpg",
  plot = combined_plot,
  device = "jpg",
  width = 21,
  height = 29.7,
  units = "cm",
  dpi = 300
)
```

```{r}
fontsize <- 4.3
plot7 <- ggplot(travel_time) +
  stat_ecdf(aes(x = sampled_time, color = "Real Data", linetype = "Real Data")) +
  stat_ecdf(aes(x = non_dependent_time, color = "Non-dependent", linetype = "Non-dependent")) +
  stat_ecdf(aes(x = first_order_time, color = "1st-order", linetype = "1st-order")) +
  stat_ecdf(aes(x = second_order_time, color = "2nd-order", linetype = "2nd-order")) +
  stat_ecdf(aes(x = population_time, color = "Population", linetype = "Population")) +
  stat_ecdf(aes(x = HMM, color = "HMM", linetype = "HMM")) +
  labs(
    title = "Empirical CDF Comparison",
    x = "Total Travel Time (seconds)",
    y = "Cumulative Probability"
  ) +
  coord_cartesian(xlim = c(0, 4000), ylim = c(0, 1)) +
  scale_color_manual(
    name = "Models",
    values = c(
      "Real Data" = "red",
      "Non-dependent" = "#1f77b4",
      "1st-order" = "#2ca02c",
      "2nd-order" = "#d19f9f",
      "Population" = "#7c48ac",
      "HMM" = "#7d3f33"
    )
  ) +
  scale_linetype_manual(
    name = "Models",
    values = c(
      "Real Data" = "solid",
      "Non-dependent" = "dashed",
      "1st-order" = "dotdash",
      "2nd-order" = "longdash",
      "Population" = "twodash",
      "HMM" = "F2"
    )
  ) +
  theme(
    panel.background = element_rect(fill = "white", colour = "black", linewidth = 1),
    panel.grid = element_line(colour = "white"),
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
    legend.position = c(0.98, 0.05),
    legend.justification = c(1, 0),
    text = element_text(size = rel(fontsize)),
    plot.title = element_text(size = rel(fontsize)),
    legend.text = element_text(size = rel(fontsize)),
    legend.key = element_rect(fill = "white")
  )
plot7
```

```{r}
plot8 <- ggplot(travel_time) +
  stat_density(aes(x = sampled_time, color = "Real Data", linetype = "Real Data"), geom = "line", bw = 50) +
  stat_density(aes(x = non_dependent_time, color = "Non-dependent", linetype = "Non-dependent"), geom = "line", bw = 150) +
  stat_density(aes(x = first_order_time, color = "1st-order", linetype = "1st-order"), geom = "line", bw = 150) +
  stat_density(aes(x = second_order_time, color = "2nd-order", linetype = "2nd-order"), geom = "line", bw = 150) +
  stat_density(aes(x = population_time, color = "Population", linetype = "Population"), geom = "line", bw = 150) +
  stat_density(aes(x = HMM, color = "HMM", linetype = "HMM"), geom = "line", bw = 150) +
  labs(
    title = "Empirical PDF Comparison",
    x = "Total Travel Time (seconds)",
    y = "Density"
  ) +
  scale_color_manual(
    name = "Models",
    values = c(
      "Real Data" = "red",
      "Non-dependent" = "#1f77b4",
      "1st-order" = "#2ca02c",
      "2nd-order" = "#d19f9f",
      "Population" = "#7c48ac",
      "HMM" = "#7d3f33"
    )
  ) +
  scale_linetype_manual(
    name = "Models",
    values = c(
      "Real Data" = "solid",
      "Non-dependent" = "dashed",
      "1st-order" = "dotdash",
      "2nd-order" = "longdash",
      "Population" = "twodash",
      "HMM" = "F2"
    )
  ) +
  theme(
    panel.background = element_rect(fill = "white", colour = "black", linewidth = 1),
    panel.grid = element_line(colour = "white"),
    legend.position = c(0.98, 0.95),
    text = element_text(size = rel(fontsize)),
    plot.title = element_text(size = rel(fontsize)),
    legend.text = element_text(size = rel(fontsize)),
    legend.justification = c(1, 1)
  )
plot8
```

```{r}
# save data
write.csv(travel_time, file = "plot/plot_data/plot4_data.csv", row.names = FALSE)
```