---
title: "Route Finder2"
author: "Mingze Li 300137754"
date: "2025-02-14"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(traveltimeCLT)
library(data.table)
library(traveltimeHMM)
library(doParallel)
library(igraph)

```

```{r}
trips = fread('data/net_stat.csv')
net <- unique(trips, by = c("linkID", "nextLinkID"))
net <- net[,.(linkID,nextLinkID,length)]
names(net)[3]<-"weight"
filted_net <- trips[trips$fictional==F,]
filted_net <- unique(filted_net, by = c("linkID", "nextLinkID"))
filted_net <- filted_net[,.(linkID,nextLinkID,length)]
names(filted_net)[3]<-"weight"
g1 <- graph_from_data_frame(filted_net, directed = TRUE)
g2 <- graph_from_data_frame(net, directed = T)
g1 <- simplify(g1, remove.multiple = TRUE, remove.loops = TRUE)
g2 <- simplify(g2, remove.multiple = F, remove.loops = TRUE)
```

```{r}
remove_duplicate_paths <- function(paths, k,type) {
  unique_paths <- list()
  for (path in paths) {
      if(type==1)path_nodes <-V(g1)$name[path]
      if(type==2)path_nodes <-V(g2)$name[path]
      is_duplicate <- any(sapply(unique_paths, function(p) identical(p, path_nodes)))
      if (!is_duplicate) {
        unique_paths <- append(unique_paths, list(path_nodes))
      }
      if (length(unique_paths) >= k) {
        break
      }
    }
    return(unique_paths)
}
calculate_path_length <- function(graph, pathset) {
  if (length(pathset) < 1) return(numeric(0))
  result<-c()
  for (paths in pathset) {
    edges <- E(graph, path = paths)
    result<-c(result,sum(edges$weight, na.rm = TRUE))
  }
result
}
calculate_expected_time<- function(graph, pathset,time="Global") {
  isTimeBin<-T
  if(!time %in% c("EveningNight", "EveningRush" , "Weekday"  ,    "MorningRush" , "Weekendday","Global"  )){isTimeBin<-F
    time <- as.POSIXct( time)
    start_time <- time
    time_Bin<-time_bins_readable(time)
    }else time_Bin<-time
    timelist <-c()
    arrivetime<-c()
  for (paths in pathset) {
      edges <- E(graph,path = paths)
      if(isTimeBin)time <- 0
      else time<-start_time
    for(edge in edges){
      if(!isTimeBin) time_Bin<-time_bins_readable(time)
      leave <- as.integer(as.vector(ends(graph, edge, names = TRUE)[1]))
      arrive <- as.integer(as.vector(ends(graph, edge, names = TRUE)[2]))
      edge_data <- trips[linkID == leave & nextLinkID == arrive & timeBin == time_Bin,]
      if (nrow(edge_data) == 0) {
        edge_data <- trips[linkID == leave & nextLinkID == arrive & timeBin == "Global",]
      }
        new_time <- exp(edge_data$one_way_mean)
      time <- time+new_time
    }
    if(isTimeBin)timelist<-c(timelist,time)
    else {
      arrivetime<-c(arrivetime,time)
      timelist<-c(timelist,as.numeric(difftime(time,start_time,  units = "secs")))
    }
  }
  return(list(expected_time=timelist,arrivetime=arrivetime))
}

findRoute <- function(start, end,time="Global", k = 1) {
  start <- as.character(start)
  end <- as.character(end)
  paths1 <- k_shortest_paths(g1, from = start, to = end, k = k, mode = "out")$vpaths
  paths2 <- k_shortest_paths(g2, from = start, to = end, k = k, mode = "out")$vpaths
  paths1<-remove_duplicate_paths(paths1,k,1)
  paths2<-remove_duplicate_paths(paths2,k,2)
  length1<-calculate_path_length(g1,paths1)
  length2<-calculate_path_length(g2,paths2)
  time1<-calculate_expected_time(g1,paths1,time)
  time2<-calculate_expected_time(g2,paths2,time)
  arrive_time1<-as.POSIXct(time1$arrivetime)
  arrive_time2<-as.POSIXct(time2$arrivetime)
  return(list(oneway = paths1,onway_legnth=length1,time1=time1$expected_time,expect_arrive_time1=arrive_time1, twoway = paths2,twoway_length=length2,time2=time2$expected_time,expect_arrive_time2=arrive_time2))
}
```

```{r}
x=findRoute(1,6494,k=3)
x
```

```{r}
findRoute(6494,1,"2025-01-02 19:08:01",k=6)
```

```{r}
findRoute(15335, 361,"MorningRush")
```

```{r}
findRoute(c(1,2,3,4,5,6), c(101,202,303,404,505,606))
```

```{r}
#findRoute(12, 23)
findRoute(12, 23,"2021/01/01 19:30")
```