---
title: "sample route2"
author: "Mingze Li 300137754"
date: "2025-03-05"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#source('traveltimeCLTfunctions.R')
library(traveltimeCLT)
library(data.table)
```


```{r}
trips <- fread('data/trips.csv')
edge_x_timeBin <-get_timeBin_x_edges(trips)
```

```{r}
id <- sample(unique(trips$trip),1000)
#id <- seq(1:1000)
sampled_1000_trips <- trips[trip %in% id, c("trip", "linkId", "time")]
sampled_1000_trips$timeBin<-time_bins_readable(sampled_1000_trips$time)
sampled_1000_trips$time<-NULL
sampled_1000_trips<-merge(sampled_1000_trips, edge_x_timeBin, by = c("linkId", "timeBin"), all.x = TRUE)
sampled_1000_trips<-na.omit(sampled_1000_trips)
sampled_time<-data.table(tripID=unique(sampled_1000_trips$trip),real_time=trips[trip %in%id, .(time[.N]-time[1]),trip]$V1)
sampled_time$real_time<-as.numeric(sampled_time$real_time)
sampled_length<-data.table(tripID=unique(sampled_1000_trips$trip),real_length=trips[trip %in%id, .(sum(length)),trip]$V1)
```



```{r}

simulated_link<-sampled_1000_trips[,.( trip=trip,
  sampled_linkId = {
  current_edges <- edge_x_timeBin[timeBin == .BY$timeBin]
  sample(current_edges$linkId, size = .N, prob = current_edges$frequency, replace = TRUE)
}), by = timeBin]


simulated_data <- merge(
  simulated_link[, .(trip, timeBin, sampled_linkId)],
  edge_x_timeBin[, .(linkId, timeBin, mean, sd, length)],
  by.x = c("sampled_linkId", "timeBin"),
  by.y = c("linkId", "timeBin"),
  all.x = TRUE
)

simulated_result <- simulated_data[, {
  n <- .N
  U <- dependent_uniform(n)
  time_sim <- sum(exp(mean + sd * qnorm(U)))
  length_sim <- sum(length)
  .(sim_time = time_sim, sim_length = length_sim)
}, by = trip]


sampled_time$simulation <- simulated_result[,2]
sampled_length$simulation <- simulated_result[,3]

```

```{r}
plot_CDF_compare(sampled_time$real_time,sampled_time$simulation,"frequency simulation")
```

````{r}
plot_CDF_compare(sampled_length$real_length,sampled_length$simulation,"global edge number simulation","total length","CDF of length",60000)
```