---
title: "Plot4"
author: "Mingze Li 300137754"
date: "2025-06-24"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
```

```{r}
travel_time <- read.csv("plot/plot_data/plot4_data.csv")
```

```{r}
fontsize <- 4.3
cdf <- ggplot(travel_time) +
    stat_ecdf(aes(x = sampled_time, color = "Real Data", linetype = "Real Data")) +
    stat_ecdf(aes(x = non_dependent_time, color = "Non-dependent", linetype = "Non-dependent")) +
    stat_ecdf(aes(x = first_order_time, color = "1st-order", linetype = "1st-order")) +
    stat_ecdf(aes(x = second_order_time, color = "2nd-order", linetype = "2nd-order")) +
    stat_ecdf(aes(x = population_time, color = "Population", linetype = "Population")) +
    stat_ecdf(aes(x = HMM, color = "HMM", linetype = "HMM")) +
    labs(
        title = "Empirical CDF Comparison",
        x = "Total Travel Time (seconds)",
        y = "Cumulative Probability"
    ) +
    coord_cartesian(xlim = c(0, 4000), ylim = c(0, 1)) +
    scale_color_manual(
        name = "Models",
        values = c(
            "Real Data" = "red",
            "Non-dependent" = "#1f77b4",
            "1st-order" = "#2ca02c",
            "2nd-order" = "#d19f9f",
            "Population" = "#7c48ac",
            "HMM" = "#7d3f33"
        )
    ) +
    scale_linetype_manual(
        name = "Models",
        values = c(
            "Real Data" = "solid",
            "Non-dependent" = "dashed",
            "1st-order" = "dotdash",
            "2nd-order" = "longdash",
            "Population" = "twodash",
            "HMM" = "F2"
        )
    ) +
    theme(
        panel.background = element_rect(fill = "white", colour = "black", linewidth = 1),
        panel.grid = element_line(colour = "white"),
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
        legend.position = c(0.98, 0.05),
        legend.justification = c(1, 0),
        text = element_text(size = rel(fontsize)),
        plot.title = element_text(size = rel(fontsize)),
        legend.text = element_text(size = rel(fontsize)),
        legend.key = element_rect(fill = "white")
    )
cdf
```

```{r}
smooth_pdf <- ggplot(travel_time) +
    stat_density(aes(x = sampled_time, color = "Real Data", linetype = "Real Data"), geom = "line", bw = 50) +
    stat_density(aes(x = non_dependent_time, color = "Non-dependent", linetype = "Non-dependent"), geom = "line", bw = 150) +
    stat_density(aes(x = first_order_time, color = "1st-order", linetype = "1st-order"), geom = "line", bw = 150) +
    stat_density(aes(x = second_order_time, color = "2nd-order", linetype = "2nd-order"), geom = "line", bw = 150) +
    stat_density(aes(x = population_time, color = "Population", linetype = "Population"), geom = "line", bw = 150) +
    stat_density(aes(x = HMM, color = "HMM", linetype = "HMM"), geom = "line", bw = 150) +
    labs(
        title = "Empirical PDF Comparison",
        x = "Total Travel Time (seconds)",
        y = "Density"
    ) +
    scale_color_manual(
        name = "Models",
        values = c(
            "Real Data" = "red",
            "Non-dependent" = "#1f77b4",
            "1st-order" = "#2ca02c",
            "2nd-order" = "#d19f9f",
            "Population" = "#7c48ac",
            "HMM" = "#7d3f33"
        )
    ) +
    scale_linetype_manual(
        name = "Models",
        values = c(
            "Real Data" = "solid",
            "Non-dependent" = "dashed",
            "1st-order" = "dotdash",
            "2nd-order" = "longdash",
            "Population" = "twodash",
            "HMM" = "F2"
        )
    ) +
    theme(
        panel.background = element_rect(fill = "white", colour = "black", linewidth = 1),
        panel.grid = element_line(colour = "white"),
        legend.position = c(0.98, 0.95),
        text = element_text(size = rel(fontsize)),
        plot.title = element_text(size = rel(fontsize)),
        legend.text = element_text(size = rel(fontsize)),
        legend.justification = c(1, 1)
    )
smooth_pdf
```